# Generated by Django 5.0.1 on 2024-02-06 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_type', models.CharField(choices=[('UL', 'Ultrasonic'), ('ST', 'Steam'), ('MA', 'Manual')], max_length=2)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('jewel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanings', to='main_app.jewels')),
            ],
        ),
    ]
