# Generated by Django 5.0.1 on 2024-02-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_cleaning_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('jewels', models.ManyToManyField(blank=True, related_name='collectors', to='main_app.jewels')),
            ],
        ),
    ]
