# Generated by Django 5.0.1 on 2024-02-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_collector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='jewels',
            field=models.ManyToManyField(related_name='collectors', to='main_app.jewels'),
        ),
    ]
